name: Deploy Recipes App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy via SSH to Webgo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBGO_SFTP_HOST }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.WEBGO_SFTP_PORT || 22 }}
          script: |
            cd /home/www/de.absolutholz.recipes
            rm -rf public # Remove old files
            mkdir -p public # Create the public directory if it doesn't exist
            tar -xzf deploy.tar.gz -C public # Extract the archive directly into public
            rm deploy.tar.gz
      - name: Create tar archive
        run: tar -czvf deploy.tar.gz dist # Create a compressed archive of the dist directory
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: deploy.tar.gz
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: next-build
