name: Deploy Recipes App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: List files after build
        run: ls -al && ls -al dist || true # List all files and check dist

      - name: Deploy via SSH to Webgo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBGO_SFTP_HOST }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.WEBGO_SFTP_PORT || 22 }}
          script: |
            echo "Current working directory on server: $(pwd)"
            ls -al /home/www/de.absolutholz.recipes
            ls -al /home/www/de.absolutholz.recipes/public
            # cd /home/www/de.absolutholz.recipes
            rm -rf /home/www/de.absolutholz.recipes/public/*
            rsync -avz --delete dist/ /home/www/de.absolutholz.recipes/public/
            ls -al /home/www/de.absolutholz.recipes/public
