name: Deploy Recipes App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Deploy via SSH to Webgo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBGO_SFTP_HOST }}
          username: ${{ secrets.WEBGO_SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.WEBGO_SFTP_PORT || 22 }}
          script: |
            cd /home/www/de.absolutholz.recipes
            rm -rf public
            mkdir -p public
            rsync -avz --delete dist/ public/ # Copy the contents of dist to public
